micronaut:
  application:
    name: microebean

  server:
    port: 9950

  multitenancy:
    tenantresolver:
      httpheader:
        enabled: true

datasource:
  default: db

  db:
    username: ag
    password:
    databaseUrl: jdbc:postgresql://127.0.0.1:5432/tenants
    databaseDriver: org.postgresql.Driver
